[package]
name = "hello-maud"
version = "0.1.0"
authors = ["Matthias Lambrecht <mats.lan.pod@googlemail.com>"]
edition = "2018"

[dependencies]
actix = "0.7.9"
actix-web = "0.7.18"
maud = { version = "*", features = ["actix-web"] }

